const fs = require('fs');

const frNew = {
  "select_all": "Tout sélectionner",
  "deselect": "Désélectionner",
  "selected_students": "Étudiants sélectionnés :",
  "selected_count": "{count} / {total} sélectionné(s)",
  "no_student_found": "Aucun étudiant ne correspond à \"{query}\"",
  "no_student_available": "Aucun étudiant disponible",
  "unnamed": "Sans nom",
  "search_student_placeholder": "Rechercher un étudiant...",
  "remove": "Retirer",
  "stay_informed": "Restez informé",
  "newsletter_title": "Recevez les actualités des formations ALREI",
  "newsletter_desc": "Recevez les annonces de nouveaux programmes, de ressources en libre accès, de webinaires, de recherches et de possibilités de participation syndicale.",
  "newsletter_email_placeholder": "Saisissez votre adresse e-mail",
  "subscribe": "S'abonner",
  "newsletter_disclaimer": "En vous abonnant, vous acceptez de recevoir les actualités d'ALREI. Vous pouvez vous désabonner à tout moment.",
  "newsletter_success": "Merci ! Vous êtes désormais abonné aux actualités ALREI.",
  "search_country_placeholder": "Rechercher un pays ou indicatif...",
  "no_country_found": "Aucun pays trouvé",
  "additional_info": "Informations complémentaires",
  "blog_info_desc": "Les détails relatifs aux candidatures, aux désignations et au calendrier définitif seront publiés sur le Centre ALREI de formation des travailleurs.",
  "view_courses": "Voir les formations",
  "manage_assignments": "Gestion des Devoirs & Travaux",
  "create_new_assignment": "Créer Un Nouveau Devoir",
  "loading_assignments": "Chargement des devoirs...",
  "min_pass_pts": "Min. valider",
  "max_pts": "Note max",
  "final_evaluation": "Évaluation Finale",
  "submissions_and_grading": "Soumissions & Notation",
  "edit_assignment": "Modifier le Devoir",
  "assignment_title": "Titre du devoir",
  "assignment_instructions": "Description / Consignes",
  "submissions": "Soumissions",
  "submitted_file": "Fichier rendu",
  "assigned_grade": "Note attribuée",
  "feedback_comments": "Commentaires / Feedback",
  "download": "Télécharger",
  "no_file": "Aucun fichier",
  "manage_quizzes": "Gestion des Questionnaires",
  "create_new_quiz": "Créer Un Nouveau Questionnaire",
  "loading_quizzes": "Chargement des questionnaires...",
  "min_pass_percent": "Min. valider",
  "manage_questions": "Gérer les Questions",
  "view_results": "Voir les Résultats",
  "edit_question": "Modifier la Question",
  "add_new_question": "Ajouter une Nouvelle Question",
  "question_text": "Énoncé de la question",
  "question_type": "Type de question",
  "points": "Points",
  "possible_answers": "Réponses possibles",
  "add_option": "Ajouter une option",
  "accepted_keywords": "Mots-clés acceptés (séparés par des virgules)",
  "explanation_feedback": "Explication / Feedback (optionnel)",
  "update_question": "Mettre à jour",
  "add_question": "Ajouter la question",
  "back_to_topics": "Retour aux sujets",
  "replies": "Réponses",
  "reply": "Répondre",
  "help_forum": "Forum d'entraide",
  "new_topic": "Nouveau sujet",
  "restricted_forum": "Forum restreint à votre langue d'inscription",
  "restricted_forum_desc": "Votre compte est configuré pour le forum {lang}. Vous ne pouvez accéder qu'à ce forum.",
  "publish_topic": "Publier le sujet",
  "open": "Ouvert",
  "closed": "Fermé",
  "take_quiz": "Passer le quiz",
  "no_quiz_available": "Aucun questionnaire disponible pour le moment.",
  "question_progress": "Question {current} sur {total}",
  "completed_percent": "{percent}% complété",
  "previous": "Précédent",
  "next": "Suivant",
  "finish_and_submit": "Terminer et Soumettre",
  "registration_confirmation": "Confirmation d'inscription",
  "verification_code_sent": "Un code de vérification à 6 chiffres a été envoyé à :",
  "confirmation_code": "Code de confirmation",
  "validate_and_confirm": "Valider & Confirmer mon compte",
  "resend_code": "Renvoyer un nouveau code"
};

const enNew = {
  "select_all": "Select all",
  "deselect": "Deselect",
  "selected_students": "Selected students:",
  "selected_count": "{count} / {total} selected",
  "no_student_found": "No student matches \"{query}\"",
  "no_student_available": "No student available",
  "unnamed": "Unnamed",
  "search_student_placeholder": "Search student...",
  "remove": "Remove",
  "stay_informed": "Stay informed",
  "newsletter_title": "Receive news on ALREI training",
  "newsletter_desc": "Receive announcements of new programs, open access resources, webinars, research, and union participation opportunities.",
  "newsletter_email_placeholder": "Enter your email address",
  "subscribe": "Subscribe",
  "newsletter_disclaimer": "By subscribing, you agree to receive news from ALREI. You can unsubscribe at any time.",
  "newsletter_success": "Thank you! You are now subscribed to ALREI news.",
  "search_country_placeholder": "Search country or dial code...",
  "no_country_found": "No country found",
  "additional_info": "Additional information",
  "blog_info_desc": "Details regarding applications, designations, and final schedules will be published on the ALREI Workers' Education Center.",
  "view_courses": "View courses",
  "manage_assignments": "Assignments & Tasks Management",
  "create_new_assignment": "Create New Assignment",
  "loading_assignments": "Loading assignments...",
  "min_pass_pts": "Min. to pass",
  "max_pts": "Max score",
  "final_evaluation": "Final Evaluation",
  "submissions_and_grading": "Submissions & Grading",
  "edit_assignment": "Edit Assignment",
  "assignment_title": "Assignment title",
  "assignment_instructions": "Description / Instructions",
  "submissions": "Submissions",
  "submitted_file": "Submitted file",
  "assigned_grade": "Assigned grade",
  "feedback_comments": "Comments / Feedback",
  "download": "Download",
  "no_file": "No file",
  "manage_quizzes": "Quizzes & Assessments Management",
  "create_new_quiz": "Create New Quiz",
  "loading_quizzes": "Loading quizzes...",
  "min_pass_percent": "Min. to pass",
  "manage_questions": "Manage Questions",
  "view_results": "View Results",
  "edit_question": "Edit Question",
  "add_new_question": "Add New Question",
  "question_text": "Question text",
  "question_type": "Question type",
  "points": "Points",
  "possible_answers": "Possible answers",
  "add_option": "Add option",
  "accepted_keywords": "Accepted keywords (comma separated)",
  "explanation_feedback": "Explanation / Feedback (optional)",
  "update_question": "Update question",
  "add_question": "Add question",
  "back_to_topics": "Back to topics",
  "replies": "Replies",
  "reply": "Reply",
  "help_forum": "Help & Discussion Forum",
  "new_topic": "New topic",
  "restricted_forum": "Forum restricted to your registration language",
  "restricted_forum_desc": "Your account is configured for the {lang} forum. You can only access this forum.",
  "publish_topic": "Publish topic",
  "open": "Open",
  "closed": "Closed",
  "take_quiz": "Take quiz",
  "no_quiz_available": "No quiz available at the moment.",
  "question_progress": "Question {current} of {total}",
  "completed_percent": "{percent}% completed",
  "previous": "Previous",
  "next": "Next",
  "finish_and_submit": "Finish & Submit",
  "registration_confirmation": "Registration confirmation",
  "verification_code_sent": "A 6-digit verification code has been sent to:",
  "confirmation_code": "Confirmation code",
  "validate_and_confirm": "Validate & Confirm my account",
  "resend_code": "Resend new code"
};

const ptNew = {
  "select_all": "Selecionar tudo",
  "deselect": "Desmarcar",
  "selected_students": "Estudantes selecionados:",
  "selected_count": "{count} / {total} selecionado(s)",
  "no_student_found": "Nenhum estudante corresponde a \"{query}\"",
  "no_student_available": "Nenhum estudante disponível",
  "unnamed": "Sem nome",
  "search_student_placeholder": "Pesquisar estudante...",
  "remove": "Remover",
  "stay_informed": "Fique informado",
  "newsletter_title": "Receba as novidades dos cursos da ALREI",
  "newsletter_desc": "Receba anúncios de novos programas, recursos de acesso livre, webinars, pesquisas e oportunidades de participação sindical.",
  "newsletter_email_placeholder": "Digite o seu endereço de e-mail",
  "subscribe": "Inscrever-se",
  "newsletter_disclaimer": "Ao inscrever-se, concorda em receber novidades da ALREI. Pode cancelar a subscrição a qualquer momento.",
  "newsletter_success": "Obrigado! Agora está inscrito nas novidades da ALREI.",
  "search_country_placeholder": "Pesquisar país ou indicativo...",
  "no_country_found": "Nenhum país encontrado",
  "additional_info": "Informações adicionais",
  "blog_info_desc": "Detalhes sobre candidaturas, indicações e calendário definitivo serão publicados no Centro ALREI de Formação dos Trabalhadores.",
  "view_courses": "Ver formações",
  "manage_assignments": "Gestão de Trabalhos & Tarefas",
  "create_new_assignment": "Criar Novo Trabalho",
  "loading_assignments": "Carregando trabalhos...",
  "min_pass_pts": "Mín. aprovação",
  "max_pts": "Nota máx.",
  "final_evaluation": "Avaliação Final",
  "submissions_and_grading": "Submissões & Avaliação",
  "edit_assignment": "Editar Trabalho",
  "assignment_title": "Título do trabalho",
  "assignment_instructions": "Descrição / Instruções",
  "submissions": "Submissões",
  "submitted_file": "Ficheiro entregue",
  "assigned_grade": "Nota atribuída",
  "feedback_comments": "Comentários / Feedback",
  "download": "Descarregar",
  "no_file": "Nenhum ficheiro",
  "manage_quizzes": "Gestão de Questionários & Testes",
  "create_new_quiz": "Criar Novo Questionário",
  "loading_quizzes": "Carregando questionários...",
  "min_pass_percent": "Mín. aprovação",
  "manage_questions": "Gerir Perguntas",
  "view_results": "Ver Resultados",
  "edit_question": "Editar Pergunta",
  "add_new_question": "Adicionar Nova Pergunta",
  "question_text": "Texto da pergunta",
  "question_type": "Tipo de pergunta",
  "points": "Pontos",
  "possible_answers": "Respostas possíveis",
  "add_option": "Adicionar opção",
  "accepted_keywords": "Palavras-chave aceites (separadas por vírgula)",
  "explanation_feedback": "Explicação / Feedback (opcional)",
  "update_question": "Atualizar pergunta",
  "add_question": "Adicionar pergunta",
  "back_to_topics": "Voltar aos tópicos",
  "replies": "Respostas",
  "reply": "Responder",
  "help_forum": "Fórum de Apoio",
  "new_topic": "Novo tópico",
  "restricted_forum": "Fórum restrito ao seu idioma de registo",
  "restricted_forum_desc": "A sua conta está configurada para o fórum de {lang}. Apenas pode aceder a este fórum.",
  "publish_topic": "Publicar tópico",
  "open": "Aberto",
  "closed": "Fechado",
  "take_quiz": "Realizar teste",
  "no_quiz_available": "Nenhum questionário disponível de momento.",
  "question_progress": "Pergunta {current} de {total}",
  "completed_percent": "{percent}% concluído",
  "previous": "Anterior",
  "next": "Seguinte",
  "finish_and_submit": "Concluir e Submeter",
  "registration_confirmation": "Confirmação de registo",
  "verification_code_sent": "Um código de verificação de 6 dígitos foi enviado para:",
  "confirmation_code": "Código de confirmação",
  "validate_and_confirm": "Validar & Confirmar minha conta",
  "resend_code": "Reenviar novo código"
};

function updateLocales(lang, newKeys) {
  const appPath = `app/locales/${lang}.json`;
  const i18nPath = `i18n/locales/${lang}.json`;
  
  const appData = JSON.parse(fs.readFileSync(appPath, 'utf8'));
  Object.assign(appData, newKeys);
  fs.writeFileSync(appPath, JSON.stringify(appData, null, 2), 'utf8');

  fs.writeFileSync(i18nPath, JSON.stringify(appData, null, 2), 'utf8');
  console.log(`Updated ${lang} locale files successfully.`);
}

updateLocales('fr', frNew);
updateLocales('en', enNew);
updateLocales('pt', ptNew);
